### ISSUE TITLE
Ambari containerization in Docker

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/clemlab-ambari#9]
# Tasks
- Research Docker.
- Describe in your research notes Docker structure, it main components, how it works, advantages and disadvantages.
- Install Docker on Ubuntu 22.04, start and stop **Hello World** container `without sudo` (check [Linux postinstallation steps](https://docs.docker.com/engine/install/linux-postinstall/)).
- Create and build Docker image that will build Ambari Server and save deb-package.
- Create and build Docker image that will install Ambari Server and start it. (Ambari might be available on port 8080).

# Useful links
- [Docker Manuals](https://docs.docker.com/manuals/)
- [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/)
- [Linux postinstallation steps](https://docs.docker.com/engine/install/linux-postinstall/)

## Completion
- [x] @YuriiBalandyuk 
- [x] @VitaliiBalaiev

**Comment by VitaliiBalaiev** [comment]
>Create and build Docker image that will build Ambari Server and save deb-package.
>Create and build Docker image that will install Ambari Server and start it. (Ambari might be available on port 8080).

Це має бути два окремих образи? Кудись потрібно буде залити чи просто відзвітуватись про виконання?

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 
До цього завдання поки ще не переходьте. Спочатку закінчіть курс по Linux та спробуйте запустити Ambari без докера. Обговоримо його в четвер.

**Comment by YuriiBalandiuk** [comment]
@Nazarii-Melnyk  Добрий день. В мене світло буде аж з 14:00-17:00. Нажаль такі графіки.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk 
Доброго дня, старайтеся підключитись хоча б з мобільного. Якщо не вдасться то подивитесь запис зустрічі пізніше.

**Comment by YuriiBalandiuk** [comment]
> @YuriiBalandyuk Доброго дня, старайтеся підключитись хоча б з мобільного. Якщо не вдасться то подивитесь запис зустрічі пізніше.

Я спробую. Якщо не захоче підключатись, то вже гляну запис. Просто я в 4 групі і сьогодні в мене біда зі світлом.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk  @VitaliiBalaiev 
Щоб виконати це завдання, створивши лише один Docker образ, для цього необхідно щоб ви реалізували механізм [Multi-stage builds](https://docs.docker.com/build/building/multi-stage/) (про нього я говорив на зустрічі).

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Що потрібно записати в нотатках на рахунок Docker?

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
`ambari-server setup` очікує вводу символу для налаштування профілю користувача, чи можна запустити його в неінтерактивному режимі, чи можливо `ambari-server setup`  не потрібен, а треба передати якийсь файл конфігу і одразу виконувати команду `ambari-server start`

**Comment by VitaliiBalaiev** [comment]
> @Nazarii-Melnyk `ambari-server setup` очікує вводу символу для налаштування профілю користувача, чи можна запустити його в неінтерактивному режимі, чи можливо `ambari-server setup` не потрібен, а треба передати якийсь файл конфігу і одразу виконувати команду `ambari-server start`

Знайшов командою ambari-server setup --help, потрібно ставити флаг --silent для  стандартних значень

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
ambari-server не стартує в контейнері. Встановив збудований пакет, зробив ambari-setup, в докерфайлі останні рядки це `CMD ["ambari-server", "start"] ` `EXPOSE 8080`, коли запускаю контейнер в логах наступне:
![image](https://github.com/user-attachments/assets/22131ac6-e5ce-45ac-b640-cd6fdb11ccfe)

Пробував також виконувати команду `RUN ambari-server start` в докерфайлі, в консолі наступне:
![image](https://github.com/user-attachments/assets/32a8296d-3789-424d-b3fa-4dde073fcab7)

В файлі `/var/log/ambari-server/ambari-server.out`, який рекомендують переглянути є така фатальна помилка: `WARNING: SQLException occurred while connecting to localhost:5432
org.postgresql.util.PSQLException: FATAL: the database system is starting up`

З налаштувань, які я робив після копіювання збудованого файлу на новий образ ubuntu:22.04 - це встановив необхідні залежності та виконав ambari-setup

**Comment by YuriiBalandiuk** [comment]
@Nazarii-Melnyk Добрий вечір. Маю запитання стосовно того, коли я збирав образ ambari-server. Куди docker з'ів пам'ять? Сам образ склався до моменту з 14ГБ, коли показав, що мало пам'яті на пристрої. Я видалив кеш докера, але не побачив тих 14ГБ на /dev/sda3. І я не можу зібрати знову, бо мій запас в 20Гб зник(директорія Ambari-server займає 15Гб з 60ГБ, я їх не беру до уваги). Куди intellij зберігає файли, які були в процесі виконання цієї команди: docker build -t ambari-clemlab . (в кінці крапка відноситься до команди, як вказівник на поточну директорію з якої докер шукає Dockerfile і залежні файли)

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev Доброго дня, як я бачу помилка вказує на проблему із базою даних, в першу чергу варто перевірити чи postgres в контейнері встановлений, запущений та доступний в той момент, коли ambari server запускається.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk 
Доброго дня, перегляньте які точки монтування займають скільки пам'яті, скільки займає пам'яті ваш кеш, особливо кеш IDEA. Окрім цього докер має команди для того, щоб перевірити скільки конкретно він займає, можливо збудовані образи кешуються декілька разів. Коротко кажучи, спочатку визначте що займає місце і чому.

**Comment by YuriiBalandiuk** [comment]
> [@VitaliiBalaiev](https://github.com/VitaliiBalaiev) Доброго дня, як я бачу помилка вказує на проблему із базою даних, в першу чергу варто перевірити чи postgres в контейнері встановлений, запущений та доступний в той момент, коли ambari server запускається.

В мене була помилка, що postgresql не встановлено на ОС. Коли при спробі стартувати, то одразу після рядка About to start PostgreSQL викидало помилку. Гадаю це не в цьому проблема.

**Comment by YuriiBalandiuk** [comment]
@Nazarii-Melnyk І в мене по графіку в 12:00 вимкнуть світло. Буду пробувати підключатись з телефона.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk Добре, але таку інформацію краще повідомляйте у нашій дискусії GitHub, адже в картці має бути 
суто інформація що стосується її виконання.

**Comment by YuriiBalandyuk** [comment]
> > [@VitaliiBalaiev](https://github.com/VitaliiBalaiev) Доброго дня, як я бачу помилка вказує на проблему із базою даних, в першу чергу варто перевірити чи postgres в контейнері встановлений, запущений та доступний в той момент, коли ambari server запускається.
> 
> В мене була помилка, що postgresql не встановлено на ОС. Коли при спробі стартувати, то одразу після рядка About to start PostgreSQL викидало помилку. Гадаю це не в цьому проблема.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 
Можливо PostgreSQL встановлений, але не може запуститись, це необхідно перевірити використовуючи systemctl. Перевірте також інші логи Ambari, логи самого сервісу СУБД. Можливо вони вкажуть на причину проблеми.

**Comment by VitaliiBalaiev** [comment]
> @VitaliiBalaiev Доброго дня, як я бачу помилка вказує на проблему із базою даних, в першу чергу варто перевірити чи postgres в контейнері встановлений, запущений та доступний в той момент, коли ambari server запускається.

Постгрес пробував і запускати окремою командою, і рестартити, і зупиняти, не допомогло. Напевно вже детальніше обговоримо на зустрічі.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Який саме файл прикріпити? Деб-пакет не підтримується ГітХабом і розмір дуже великий.

[Нову гілку створив і запушив туди докерфайл.](https://github.com/TNTU-RS-internship/clemlab-ambari/tree/9-ambari-containerization-in-docker)

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Тоді закоміть і запуш цей deb-пакет у новій гілці, яку ти створив. Потім цей коміт можна буде видалити, використовуючи наприклад інтерактивний rebase.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
При пуші помилка: remote: error: File ambari-server_2.7.9.0-0-dist.deb is 541.14 MB; this exceeds GitHub's file size limit of 100.00 MB        

Можливо на якийсь інший хостинг залити?

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev Окремо також Віталій щодо твого питання по RUN, CMD, ENTRYPOINT, я трохи неточно описав їх на зустрічі, ось коротко і простими словами:
- `RUN` - виконується тільки на стадії будування образу (коли виконується команда `build`)
- `CMD` - таких команд може бути декілька в Dockerfile, і суть цієї команди що вона може виконатися як є (за замовчуванням), а може бути перевизначена при запуску (можеш уявити це так ніби ти перевизначаєш параметри у програми, як ти це робив в Maven з версією jdk).
- `ENTRYPOINT` - ця інструкція може бути тільки одна в Dockerfile і запускає команду, яка буде виконуватися впродовж усієї роботи контейнера (тобто саме цією інструкцією варто запускати Ambari Server).

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Тоді не варто завантажувати, я тоді просто візьму гілку в якій ти будував пакет і збудую його в себе сам

**Comment by VitaliiBalaiev** [comment]
> @VitaliiBalaiev Окремо також Віталій щодо твого питання по RUN, CMD, ENTRYPOINT, я трохи неточно описав їх на зустрічі, ось коротко і простими словами:

@Nazarii-Melnyk 
Зрозуміло, дуже дякую! Зміню в докерфайлі з CMD на ENTRYPOINT.

**Comment by YuriiBalandiuk** [comment]
![Image](https://github.com/user-attachments/assets/3662024a-29d2-40f3-a9f4-d92c26beee70)


@Nazarii-Melnyk  Але ж тут сказано, що CMD інструкція має бути одна в Dockerfile або буде виконуватись останній CMD.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 
Так, вірно, дякую за поправку. Відповідно до документації і CMD і ENTRYPOINT можна використати тільки один раз, при цьому хоча б одну з цих двох команд необхідно вказати для запуску контейнера. Також їх можна комбінувати - в той час як ENTRYPOINT визначає команду, яка незмінна для кожного запуску, то в свою чергу CMD може визначати параметри за замовчуванням для команди в ENTRYPOINT, які можна перевизначити при запуску контейнера. 
В загальному суть цих команд все ще залишається тою ж, CMD можна перевизначити, а ENTRYPOINT ні.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
В цілях експерименту ще раз скопіював пакет збудований локально у контейнер, встановив тільки Python 3 i JDK8, виконав setup без параметру --skip-view-extraction. Та сама помилка все ще залишається.

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev Проблема все ще з views?

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk Щоб розібратись що займає пам'ять використовуйте також `du`, перегляньте які аргументи додатково потрібно додати щоб команда не виводила повністю весь список файлів у піддиректоріях і можна було нормально знайти що займає найбільше місця. Окрім цього добре буде якщо ви розберетеся як збільшити обсяг вільного місця для віртуальної машини, але якщо не вийде то в крайньому випадку просто перестворіть її.

Також розберіться з самим Docker, чому він у вас не запускається.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Виходить, що в при білді в контейнері чомусь папка views не додається, пакет білдиться без неї, хоча Maven команда така сама. Відповідно, і сам пакет в контейнері важить на 300мб менше. Але я скопіював пакет у контейнер, який білдив локально, той що сам встановив, налаштував, запустив і перевірив, я кидав результати під карткою №1. В ньому хоч і є папка views, але помилка залишається такою самою, виходить проблема не у папці views? Можу поділитись [логами за посиланням.](https://pastebin.com/2nfiZWYR)

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Кидайте помилки які у вас виникають сюди, їх можна виділити знаками ``` зверху і знизу.

Це буде виглядати так:
```
Текст
```

У мене просто інша ситуація, я збудував пакет локально з вашої гілки `internship-2.7.9.0-python3` і спробував одразу його встановити/запустити без контейнера, але проблема з views така ж, як і в контейнері. Я ще гляну до цього сьогодні ввечері.

Ще одне питання, ви білдили Ambari Server раніше разом з усім проєктом Ambari, а в контейнері тільки Ambari Server з усіма необхідними компонентами для нього?

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
> я збудував пакет локально з вашої гілки internship-2.7.9.0-python3 і спробував одразу його встановити/запустити без контейнера, але проблема з views така ж, як і в контейнері

А ви будували тільки Ambari Server з параметрами `--projects ambari-server --also-make`? 

> Ще одне питання, ви білдили Ambari Server раніше разом з усім проєктом Ambari, а в контейнері тільки Ambari Server з усіма необхідними компонентами для нього?

Спочатку через неуважність локально білдив всі 51 компоненти, в мене це вийшло, потім дописав до команди параметри `--projects ambari-server --also-make`, збілдив відповідно тільки 8 компонентів - Ambari Server та залежні для нього і встановив пакет, який знаходився у ambari-server/target/. В контейнері запускав тільки команду для білду разом з `--projects ambari-server --also-make`

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Так, вірно, я будував також тільки ambari-server. 
В мене просто була підозра що у вас локально все ще старий deb пакет, який був збудований в процесі білду всього проєкту, і можливо це також вплинуло що у нас зараз такі різні ситуації (хоч такого і не мало б бути). Спробуйте зберегти цей deb-пакет що у вас локально в якусь іншу директорію, виконати очищення `mvn 
-B clean` і після  збудувати тільки Ambari-Server. Перегляньте чи буде проблема з views.

Я в себе запустив на фоні білд всього проєкту Ambari, згодом перевірю чи моя догадка вірна.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
В мене також була підозра, що це старий деб-пакет, у якому є всі-всі необхідні компоненти.
Зараз спробую все очистити і збудувати локально тільки Ambari Server.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Почистив mvn -B clean, видалив старий пакет, збілдив новий через  --projects ambari-server --also-make,встановив цей новий, setup без проблем, start без проблем, але тепер при переході на localhost:8080 - 403 помилка. Здається в вас було те саме? 

Але при цьому, папка views в пакеті є. При сетапі також не було жодного повідомлення про відсутність. Якась дивна поведінка.

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Ти виконав був setup з параметром `--skip-view-extraction`?

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Ні, setup виконував без жодних додаткових параметрів, тільки `ambari-server setup` і обирав дефолтні значення.

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Покажіть тоді файли логів ambari-server.log або ambari-server.out, на яку помилку вони вказують.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
В ambari-server.out: 
```
Jul 17, 2024 4:07:32 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public void org.apache.ambari.server.orm.dao.AmbariConfigurationDAO.create(java.lang.Object)] is synthetic and is being intercepted by [org.apache.ambari.server.orm.AmbariJpaLocalTxnInterceptor@2241f05b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jul 17, 2024 4:07:32 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public void org.apache.ambari.server.orm.dao.RepositoryVersionDAO.create(java.lang.Object)] is synthetic and is being intercepted by [org.apache.ambari.server.orm.AmbariJpaLocalTxnInterceptor@2241f05b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jul 17, 2024 4:07:32 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public void org.apache.ambari.server.orm.dao.HostVersionDAO.create(java.lang.Object)] is synthetic and is being intercepted by [org.apache.ambari.server.orm.AmbariJpaLocalTxnInterceptor@2241f05b]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jul 17, 2024 4:07:33 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public java.lang.Object org.apache.ambari.server.topology.tasks.ConfigureClusterTask.call() throws java.lang.Exception] is synthetic and is being intercepted by [org.apache.ambari.server.security.authorization.internal.InternalAuthenticationInterceptor@5f174dd2]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Database consistency check result: DB_CHECK_SUCCESS
log4j:WARN No such property [fileNamePattern] in org.apache.log4j.RollingFileAppender.
```
В ambari-server.log близько тисячі стрічок, скопіював ті стрічки, які позначені [ERROR]:
```
2024-07-17 16:07:37,229 ERROR [Stack Version Loading Thread] URLStreamProvider:357 - Can't get secure connection to https://archive.clemlab.com/ODP/odp_urlinfo.json.  Truststore path or password is not set.
2024-07-17 16:07:37,230 ERROR [main] StackContext:189 - Could not load repo results
java.lang.IllegalStateException: Can't get secure connection to https://archive.clemlab.com/ODP/odp_urlinfo.json.  Truststore path or password is not set.
	at org.apache.ambari.server.controller.internal.URLStreamProvider.getSSLConnection(URLStreamProvider.java:358)
	at org.apache.ambari.server.controller.internal.URLStreamProvider.processURL(URLStreamProvider.java:196)
	at org.apache.ambari.server.controller.internal.URLStreamProvider.processURL(URLStreamProvider.java:155)
	at org.apache.ambari.server.controller.internal.URLStreamProvider.readFrom(URLStreamProvider.java:129)
	at org.apache.ambari.server.controller.internal.URLStreamProvider.readFrom(URLStreamProvider.java:134)
	at org.apache.ambari.server.state.stack.RepoUrlInfoCallable.call(RepoUrlInfoCallable.java:97)
	at org.apache.ambari.server.state.stack.RepoUrlInfoCallable.call(RepoUrlInfoCallable.java:50)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2024-07-17 16:07:37,859 ERROR [main] ViewRegistry:2074 - The Ambari server version 2.7.9.0 is greater than the configured maximum Ambari version 2.5.* for view PIG{1.0.0}
```

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
А раніше ambari-server запускався без проблем наскільки я пам'ятаю, і білд виконувався таким самим чином?

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Так, але можливо це знову ж таки був повністю збудований старий пакет. Я встановлював і запускав ambari-server вже після того як перебілдив з параметром ` --projects ambari-server --also-make`. Ніяких проблем не виникало.

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev @YuriiBalandyuk 

Дивно, схоже потрібно буде довше розбиратися з цією проблемою, але в мене на жаль немає так багато часу (я й так вже трохи задовго сиджу над цим). Давайте зробимо так, спробуйте сьогодні/завтра вирішити цю проблему, ось що можу порекомендувати:
1. Схоже проблема все ж не залежить від того чи будувати повністю проєкт, чи тільки Ambari Server, тому продовжуйте будувати тільки Ambari Server.
3. Так як раніше вам вдалось запустити Ambari Server, постарайтесь повернутися до минулого робочого варіанту. Перевірте чи працюють старі ваші збудовані deb-артефакти;
4. Спробуйте повністю очистити кеш, тобто залежності Yarn, Bower, Maven (вони кешуються у вашій домашній директорії в папці .cache)
5. Повністю очистіть стару збірку у ваших директоріях проєкту виконавши `mvn -B clean`, перевірте чи повністю видалились залежності bower, yarn, та їх lock-файли. В разі чого видаліть їх вручну.
6. Повністю видаліть ambari-server разом з усіма директоріями з конфігурацією, логами та залежностями.
5. Видаліть базу даних, яку використовує Ambari в postgresql.
7. Спробуйте заново перебудувати Ambari Server, встановити і перевірити його роботу.

Якщо проблема все ще залишиться, я тоді підготую вам робочу гілку 2.7.8.0, щоб ви могли збудувати Ambari Server з неї, в ній ще використовується Python 2. З нею проблем не повинно бути і вам вдасться доробити це завдання з докером.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Видалив пакет, який створився після побудови через `--projects ambari-server --also-make`, встановив старий. Старий пакет (той, який створився при побудові всіх 51 компонентів) на локальній машині чудово працює. Спробую зараз виконати ваші рекомендації і запустити тільки Ambari Server, якщо не вийде, то збудувати всі компоненти у контейнері і запустити, може щось зміниться

**Comment by Nazarii-Melnyk** [comment]
@VitaliiBalaiev 
Дивно, що цей ваш старий пакет не працює в контейнері, а цілком працює без нього, хоча умови повинні бути ті самі. 

Спробуйте ще запустити контейнер з параметром `--privileged`. Також варто очищувати збудований образ і його закешовані шари (або вказувати спеціальний параметр, щоб докер не використовував кеш при білді образу)

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Запуск контейнера з параметром --privileged не допоміг.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 
Зрозумів, тоді пробуйте виконати завдання, збудувавши Ambari Server з гілки internship-2.7.8.0-python3.

**Comment by YuriiBalandiuk** [comment]
> [@YuriiBalandyuk](https://github.com/YuriiBalandyuk) [@VitaliiBalaiev](https://github.com/VitaliiBalaiev) Зрозумів, тоді пробуйте виконати завдання, збудувавши Ambari Server з гілки internship-2.7.8.0-python3.

@Nazarii-Melnyk В мене не складається проєкт. Викидає помилку на ambari metrics.

![Image](https://github.com/user-attachments/assets/f6075153-bc14-4a8f-952c-eb94b89975b5)

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk 
Ambari Metrics не потрібно збирати, тільки Server.

**Comment by YuriiBalandiuk** [comment]
> [@YuriiBalandyuk](https://github.com/YuriiBalandyuk) Ambari Metrics не потрібно збирати, тільки Server.

Він ж входить до залежних компонентів. Я так само будую лише 8, як і будував раніше. Але зараз вже є помилка з цим.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk Так, пам'ятаю я вже таку проблему бачив, якщо я правильно пам'ятаю це через те що цей пакет javax було видалено з Java 11, перевірте яка версія Java у вас встановлена та використовується, якщо проблема все ще залишається то знайдіть і додайте необхідні залежності в maven.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 

Чи вдалось вам таки збудувати робочий артефакт Ambari Server з іншої гілки?

**Comment by YuriiBalandiuk** [comment]
> @YuriiBalandyuk @VitaliiBalaiev
> 
> Чи вдалось вам таки збудувати робочий артефакт Ambari Server з іншої гілки?

@Nazarii-Melnyk Мені не вдалось повністю збудувати. Виникали проблеми із залежностями. Повернувся назад до гілки 2.7.9.0 все з будувалось добре. Але також помітив іншу проблему. Якщо збудувати весь проєкт, то сам Ambari Server будується без проблем, якщо клонувати новий проєкт і не будувати всі 51 компонент, то в мене вже він не будується. Не знаю з чим це повʼязано (скоріше за все тоді завантажуються інші залежності, які дозволяють це зробити або я використовую не повну команду. Хоч повторюсь із повністю збудованим Ambari все стартує). Так само в контейнері в докері. Вчора пробував збудувати там, також не хотіло. Спробував збудувати весь проєкт, але вже не встиг. Спробую ввечері ще раз. І ще в мене проблема з віртуалізацією. Після того, як виключають світло вона пропадає, але в VB вона включена і на комп’ютері також. Я не рішив ще це питання з нею.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk 
Тобто коли будується весь проєкт, то Ambari Server у вас запускався без проблем і в докері?

**Comment by YuriiBalandiuk** [comment]
> @YuriiBalandyuk Тобто коли будується весь проєкт, то Ambari Server у вас запускався без проблем і в докері?

@Nazarii-Melnyk Так, відповідно і без докера та само.

**Comment by VitaliiBalaiev** [comment]
> @YuriiBalandyuk @VitaliiBalaiev
> 
> Чи вдалось вам таки збудувати робочий артефакт Ambari Server з іншої гілки?

На локальній машині гілка 2.8.8.0 будується без проблем, в докері не хоче, зробив вчора нову гілку, де оновив залежності, які стосуються пакету javax, ця проблема пропала, з'явилась інша. 
Зараз спробую в цілях експерименту просто скопіювати вже збудований пакет, глянути чи він хоча б стартує

**Comment by Nazarii-Melnyk** [comment]
Так, в основному ситуацію я зрозумів.

- @YuriiBalandyuk, так як у вас в результаті таки вдалось запустити Ambari в докері, то можете комітити сам цей докерфайл в своїй окремій гілці, щоб можна було його переглянути на GitHub.
- @VitaliiBalaiev, спробуйте ще 1 раз запустити Ambari Server в докері, якщо він коректно запуститься і працюватиме то добре, якщо все ж ні, то спробуйте додати публічний репозиторій clemlab (потрібно завантажити файл за URL https://archive.clemlab.com/ubuntu22-python3/ambari-release/2.7.9.0.0-110/ambari.list, і перемістити в папку /etc/apt/sources.list.d, перегляньте додатково вміст файлу щоб зрозуміти навіщо ви робите це). Після `apt update --allow-insecure-repositories` ви зможете встановити ambari-server з віддаленого репозиторію від самих Clemlab. (`apt install ambari-server --allow-unauthenticated`). Зверніть ще увагу на ці параметри, спробуйте спочатку виконати команди без них і подивіться яку помилку вам повертає apt. Якщо буде цікаво то пізніше можете почитати для чого підписують репозиторії і як це робиться, якими утилітами. Цей Ambari Server має точно запуститись без проблем, підкоригуйте відповідно  докерфайл щоб сервер запустився і в контейнері.

На зустрічі переглянемо ваші докерфайли і обговоримо.

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 
І прив'яжіть свої гілки до цієї картки в секції `Development`

**Comment by Nazarii-Melnyk** [comment]
@YuriiBalandyuk @VitaliiBalaiev 

Ваші гілки підпишіть власним прізвищем, наприклад `9-ambari-conteinerisation-docker-VBaliev`. Тобто Віталій перейменуй свою гілку, та що прив'язана. Окрім цього, Віталій, не бачу у цій твоїй прив'язаній гілці докерфайлу.

Юрій, якщо ти цього ще не зробив, то запуш свою гілку в якій ти писав Dockerfile, дай їй назву `9-ambari-conteinerisation-docker-YBalandyuk` і прив'яжи її до цієї карточки.

Створіть і пул реквести, щоб я міг ці файли рев'ювнути. Самі не мерджіть зміни.

**Comment by VitaliiBalaiev** [comment]
@Nazarii-Melnyk 
Додав два варіанти докерфайлів, перейменував гілку і створив пул реквест. Напевно краще буде відв'язати гілку поки, щоб картка не закрилась?

**Comment by Nazarii-Melnyk** [comment]
Так, картку я сам вже закрию з пул реквестами, головне гілки до картки прив'яжіть
